/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package SeleniumStarting.app;

import java.util.List;
import java.util.ArrayList;

import SeleniumStarting.list.LinkedList;

import static SeleniumStarting.utilities.StringUtils.join;
import static SeleniumStarting.utilities.StringUtils.split;
import static SeleniumStarting.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.By;

public class App {

    private static List<Senator> getSenators(List<WebElement> lst) {
        List<Senator> senators = new ArrayList<>();
        for (WebElement row: lst) {
            List<WebElement> components = row.findElements(By.tagName("td"));
            String name = components.get(0).findElement(By.tagName("a")).getText();
            name = name.substring(0, name.indexOf(" ("));
            String state = components.get(1).getText();
            String party = components.get(2).getText();
            String classNum = components.get(3).getText();
            senators.add(new Senator(name, state, party, classNum));
        }
        return senators;
    }

    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result));
        // Use options to run headless
        // Only has a default constructor
        ChromeOptions options = new ChromeOptions();
        // Add arguments, method uses varargs
        // options from https://developers.google.com/web/updates/2017/04/headless-chrome
        // options.addArguments("--headless",
        //     "--disable-gpu");
        WebDriver driver = new ChromeDriver(options);

        driver.navigate().to("https://www.senate.gov/senators/index.htm");

        WebElement wrapperDiv = driver.findElement(By.id("listOfSenators_wrapper"));

        WebElement btns = wrapperDiv.findElement(By.className("dt-buttons"));

        WebElement showBtn = btns.findElement(By.className("buttons-collection"));

        showBtn.click();

        WebElement changeDiv = btns.findElement(By.className("dt-button-collection"));

        // Select 100
        List<WebElement> opts = changeDiv.findElements(By.tagName("button"));
        opts.get(2).click();

        WebElement tableBody = wrapperDiv.findElement(By.tagName("tbody"));

        List<WebElement> senatorRows = tableBody.findElements(By.tagName("tr"));

        List<Senator> senators = getSenators(senatorRows);
        System.out.println(senators);
    }
}
